name: Generate Daily Articles

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch: {}

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate content
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          IMAGE_PROVIDER: unsplash
          CONTENT_BASE_DIR: content
          ARTICLES_PER_DAY: 10
          INLINE_IMAGES: 2
        run: |
          python -m content_bot generate --count ${ARTICLES_PER_DAY}

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add content
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore(content): add daily generated articles"
            git push
          fi
