name: Generate Daily Articles

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch: {}

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: content-generation
      cancel-in-progress: true
    env:
      CONTENT_BASE_DIR: content/water
      ARTICLES_PER_DAY: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Preflight env check
        env:
          LLM_PROVIDER: ${{ vars.LLM_PROVIDER || 'gigachat' }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GIGACHAT_CLIENT_ID: ${{ secrets.GIGACHAT_CLIENT_ID }}
          GIGACHAT_CLIENT_SECRET: ${{ secrets.GIGACHAT_CLIENT_SECRET }}
          GIGACHAT_BASIC: ${{ secrets.GIGACHAT_BASIC }}
        run: |
          set -e
          echo "LLM_PROVIDER=${LLM_PROVIDER}"
          if [ "${LLM_PROVIDER}" = "gigachat" ]; then
            if [ -z "$GIGACHAT_BASIC" ] && { [ -z "$GIGACHAT_CLIENT_ID" ] || [ -z "$GIGACHAT_CLIENT_SECRET" ]; }; then
              echo "GIGACHAT creds are EMPTY"; exit 1; else echo "GIGACHAT creds are SET"; fi
          else
            if [ -z "$OPENAI_API_KEY" ]; then echo "OPENAI_API_KEY is EMPTY"; exit 1; else echo "OPENAI_API_KEY is SET"; fi
          fi

      - name: Prepare git config
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Show git info
        run: |
          set -x
          git --version
          git status -sb || true
          git remote -v || true
          echo "Branch: ${GITHUB_REF} / ${GITHUB_REF_NAME}"

      - name: Write water topics file
        run: |
          mkdir -p scripts
          cat > scripts/topics.water.txt <<'EOF'
Водоподготовка для дома: ключевые этапы и ошибки
Фильтрация воды: сравнение технологий (угольные, мембранные, ионный обмен)
Очистка воды для дачи: бюджетные решения и обслуживание
Экология и вода: влияние очистных сооружений на природу
Интересные факты о воде и её фильтрации для здоровья
EOF

      - name: Generate content (text-only)
        env:
          LLM_PROVIDER: ${{ vars.LLM_PROVIDER || 'gigachat' }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GIGACHAT_CLIENT_ID: ${{ secrets.GIGACHAT_CLIENT_ID }}
          GIGACHAT_CLIENT_SECRET: ${{ secrets.GIGACHAT_CLIENT_SECRET }}
          GIGACHAT_BASIC: ${{ secrets.GIGACHAT_BASIC }}
          ARTICLES_PER_DAY: ${{ env.ARTICLES_PER_DAY }}
        run: |
          set -e
          python -m content_bot generate --count ${ARTICLES_PER_DAY} --topics-file scripts/topics.water.txt --target-chars 1000 --output-dir content/water
          [ -d "content/water" ] && [ -n "$(ls -A "content/water" 2>/dev/null || true)" ] || {
            echo "No generated content found";
            exit 1;
          }

      - name: List generated files
        run: |
          echo "Listing content/water (if exists)"
          if [ -d "content/water" ]; then
            ls -R "content/water" || true
          else
            echo "Directory content/water does not exist"
          fi

      - name: Create pull request with generated content
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(content): add daily generated articles"
          title: "chore(content): add daily generated articles"
          body: |
            Automated text-only content generation.
            - LLM: ${{ vars.LLM_PROVIDER || 'gigachat' }}
            - Articles: ${{ env.ARTICLES_PER_DAY }}
          branch: bot/daily-content
          branch-suffix: timestamp
          add-paths: |
            content/water/**
