name: Generate Articles (Text Only)

on:
  workflow_dispatch: {}

jobs:
  gen:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write topics (water)
        run: |
          mkdir -p scripts
          cat > scripts/topics.water.txt <<'EOF'
Водоподготовка для дома: ключевые этапы и ошибки
Фильтрация воды: сравнение технологий (угольные, мембранные, ионный обмен)
Очистка воды для дачи: бюджетные решения и обслуживание
Экология и вода: влияние очистных сооружений на природу
Интересные факты о воде и её фильтрации для здоровья
EOF

      - name: Generate content (text-only)
        run: |
          python -m content_bot generate --count 3 --topics-file scripts/topics.water.txt --target-chars 1000 --output-dir content/water

      - name: Show generated
        run: |
          ls -R content/water || true

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add content/water
          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi
          git commit -m "content: add water articles"
          git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO}.git" HEAD:"${BRANCH}"
